config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :seller_pages, path: 'store' do
    resources :reviews
    resources :products
    get '/otp_verification' => 'seller_pages#verify'
  end
  resources :users, :only => [:update]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  root 'home#index'
  get 'cities/:state', to: 'application#cities'
  get '/edit_profile' => 'home#edit_profile'
end

app/models/seller_page.rb
# frozen_string_literal: true

class SellerPage < ApplicationRecord
  
  belongs_to :user
  has_many :products, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :business_info, :region, :city, :phone_number, :messenger_url, presence: true
  validates :business_name, presence: true, uniqueness: true
  validates :phone_number, format: { with: /\A\d+\z/, message: "cannot have letters." }
  validates :phone_number, length: {minimum: 10, maximum: 10}
  validates :phone_number, uniqueness: true
  
  paginates_per 3

  # FriendlyID Gem
  extend FriendlyId
  friendly_id :business_name, use: :slugged
end

app/controllers/seller_pages_controller.rb
class SellerPagesController < ApplicationController
  before_action :auth_region
  before_action :set_seller_page, only: %i[ show edit update destroy ]

  # Authy Verification
  def verify
    @seller_page = current_user.seller_page
    if params[:token].present? && params[:seller_page_id].present?
      AuthyVerification.new(params[:token], params[:seller_page_id])
      if !@seller_page.verified?
        flash[:notice] = "Sorry, the code you entered is invalid. Please try again."
        render action: 'verify'
      else
        redirect_to seller_page_path(@seller_page), notice: "Seller page was successfully updated."
      end
    else
      flash[:notice] = "Please enter the OTP sent to your phone."
      render action: 'verify'
    end
  end

  # GET /seller_page
  def index
    if params[:user][:city].present? && params[:user][:region].present?
      @seller_pages = SellerPage.where(city: params[:user][:city]).page params[:page]
      if @seller_pages.empty?
        @seller_pages = SellerPage.where(region: params[:user][:region]).page params[:page]
        if @seller_pages.empty?
          flash[:notice] = "Sorry no results found."
        end
      end
      # if we want to not display current_user's seller_page
      # .and(SellerPage.where.not user_id: current_user.id)
    end
  end

  def show
  end

  # GET /seller_pages/new
  def new
    if current_user.seller_page.nil?
      @seller_page = SellerPage.new
    else
      redirect_to seller_page_path(current_user.seller_page.id)
    end
  end

  # GET /seller_pages/:id/edit
  def edit
  end

  # POST /seller_pages
  def create
    @seller_page = SellerPage.new(seller_page_params)
    @seller_page.user_id = current_user.id
    if @seller_page.save
      AuthyRegistration.new(current_user.id, params[:seller_page][:phone_number])
      AuthyRequest.new(current_user.seller_page.authy_id)
      redirect_to seller_page_otp_verification_path(current_user.seller_page.slug), notice: "Please verify your account by entering the One-Time Password sent to your mobile number."
    else
      flash[:alert] = "Invalid OTP"
      render action: 'new'
    end
  end

  # PATCH/PUT /seller_pages/:id
  def update
    if @seller_page.update(seller_page_params)
      @seller_page.update(slug: seller_page_params[:business_name].gsub(/\s+/, "-"))
      if @seller_page.saved_change_to_attribute?("phone_number")
        AuthyRemoveUser.new(current_user.id)
        AuthyRegistration.new(current_user.id, params[:seller_page][:phone_number])
        @seller_page.update(verified: false)
        if @seller_page.verified == false
          AuthyRequest.new(current_user.seller_page.authy_id)
        end
        redirect_to seller_page_otp_verification_path(current_user.seller_page.id), notice: "Please verify your account by entering the One-Time Password sent to your mobile number."
      else
        redirect_to seller_page_path(@seller_page), notice: "Seller page was successfully updated."
      end
    else
      render action: 'edit'
    end
  end

  # DELETE /seller_pages/:id
  def destroy
    AuthyRemoveUser.new(current_user.id)
    @seller_page.destroy
    redirect_to root_path, notice: "Seller page was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller_page
      @seller_page = SellerPage.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def seller_page_params
      params.require(:seller_page).permit(:business_name, :business_info, :verified, :phone_number, :region, :city, :user_id, :slug, :messenger_url)    
    end
end

app/helpers/seller_pages_helper.rb
module SellerPagesHelper
end

app/views/seller_pages/_form.html.erb
<%= form_for(@seller_page) do |form| %>
  
  <div class="card shadow-2xl bg-gray-50">
  <div class="card body px-10 py-10">
  <div class="flex justify-center">
    <div class="card shadow-inner lg:card-side bg-primary text-primary-content w-full mb-4" data-theme="bumblebee">
      <div class="card-body">
      <%if current_page?(new_seller_page_path)%>
        <h1 class="text-center text-3xl font-bold flex justify-center items-center">Create Seller Page <i class='bx bxs-note ml-4'></i></h1>
        <% else %>
        <h1 class="text-center text-3xl font-bold flex justify-center items-center">Edit Seller Page <i class='bx bxs-edit-alt ml-4' ></i></i></h1>
        <% end %>
      </div>
    </div>
  </div>
    <div class="form-control" data-theme="bumblebee">
      <%= form.label :business_name, class:"label" %>
      <div class="flex flex-col justify-center gap-x-2.5">
        <%= form.text_field :business_name, autofocus: true, autocomplete: "business name", class:"w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
      </div>
      <div class="form-control" data-theme="bumblebee">
      <%= form.label :messenger_link, class:"label" %>
      <div class="flex flex-col justify-center gap-x-2.5">
        <%= form.text_field :messenger_url, autofocus: true, autocomplete: "messenger link",placeholder:"fb.me/msg/<facebook username>", class:"w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
      </div>
      <div class="form-control">
        <%= form.label :business_info, class:"label" %>
        <div class="flex flex-col justify-center gap-x-2.5">
          <%= form.text_area :business_info, autofocus: true, autocomplete: "business info", class:" textarea h-24 textarea-bordered border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
        </div>
        <div class="form-control">
          <%= form.label :phone_number, class:"label" %>
          <div class="flex flex-row justify-center gap-x-2.5">

            <input class="w-1/6 border border-gray-300 px-3 py-2 rounded-lg shadow-inner focus:outline-none text-gray-600 focus:border-orange-primary focus:ring-1 focus:ring-orange-primary" disabled value="+63"></form>
            <%= form.text_field :phone_number, autofocus: true, autocomplete: "phone number", class:"w-5/6 border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
          </div>
          <div class="mb-4">
            <%= form.hidden_field :region, value: current_user.region %>
          </div>
          <div class="mb-4">
            <%= form.hidden_field :city, value: current_user.city %>
          </div>
          <%= form.submit class:"btn btn-primary-content shadow-lg"%>
        </div>
      </div>
  </div>
    <% end%>

app/views/seller_pages/edit.html.erb
<% if @seller_page %>
  <div class="card shadow h-full">
<%= form_for(@seller_page) do |form| %>
  <% if @seller_page.errors.any? %>
    
      <div class="m-2 text-center items-center mb-2">
      <div class="p-2 flex justify-center">
        <div class="flex justify-center items-center bg-white leading-none text-pink-600 rounded-full p-2 shadow text-teal text-sm">
          <span class="flex bg-red-600 text-white rounded-full h-6 px-3 justify-center items-center">Error!</span>
    <% @seller_page.errors.each do |error| %>
    <ul>
          <li><span class="px-2"><%= error.full_message %></span></li>
    </ul>
      <% end %>
        </div>
      </div>
  <% end %>
  <% end %>
  <div class=" card-body  bg-base-200" data-theme="bumblebee">
  
    <div class="flex justify-center">
      <div class="flex justify-center mt-12">
        <div class="flex justify-center">
          <%= render 'form', seller_page: @seller_page %>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/seller_pages/index.html.erb
<%# <h1>Hello! View other seller pages here!</h1> %>
<div class="card bordered">
<div class="card-body">
<% if @seller_pages %>

<div class="flex justify-between items-center mt-4">
      <%= link_to root_path, class:"btn btn-primary-content" do %>
    <i class='bx bx-arrow-back text-lg' ></i>
    <% end %><%= paginate @seller_pages %>
      </div>

  <% @seller_pages.each do |seller| %>
  <div class="card lg:card-side shadow-lg bg-gray-50 mb-6 mt-6" data-theme="bumblebee">
  <div class="card-body">
    <h2 class="card-title items-center"><%= seller.business_name %>
    <div class="badge badge-primary mx-2"><%= seller.region %>, <%= seller.city%></div>
    <% if seller.verified? %>
      
    <div class="badge badge-success mx-2">Verified</div>
    <% end %>
    </h2> 
    <p><%= seller.business_info %></p> 
    <div class="justify-end card-actions">
    <%= link_to seller_page_path(seller.slug) do%>
      <button class="btn btn-primary">Show</button> 
      <% end %>
      
    </div>
  </div>
</div>

<% end %>



  <br>
<% end %>

    
</div>
</div>

app/views/seller_pages/new.html.erb
<div class="card shadow h-full">
  <%= form_for(@seller_page) do |form| %>
  <% if @seller_page.errors.any? %>
    
      <div class="m-2 text-center items-center mb-2">
      <div class="p-2 flex justify-center">
        <div class="flex justify-center items-center bg-white leading-none text-pink-600 rounded-full p-2 shadow text-teal text-sm">
          <span class="flex bg-red-600 text-white rounded-full h-6 px-3 justify-center items-center">Error!</span>
    <% @seller_page.errors.each do |error| %>
    <ul>
          <li><span class="px-2"><%= error.full_message %></span></li>
    </ul>
      <% end %>
        </div>
      </div>
  <% end %>
  <% end %>
  <div class=" card-body  bg-base-200" data-theme="bumblebee">
  
    <div class="flex justify-center">
      <div class="flex justify-center mt-12">
        <div class="flex justify-center">
          <%= render 'form', seller_page: @seller_page %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/seller_pages/show.html.erb
<% if @seller_page %>
<div data-theme="bumblebee" class="mt-4 max-w-full grid grid-cols-1 md:grid-cols-2 lg:grid-rows-3 grid-flow-col gap-6">
<div class="card shadow-2xl row-span-3">
  <figure class="flex justify-center bg-primary-content">
    <%= image_tag('sellerpage.svg', class:"max-w-sm") %>
  </figure> 
  <div class="card-body">
    <h2 class="card-title flex items-center"><%= @seller_page.business_name %>
      <% if @seller_page.verified? %>
       <div class="badge mx-2 bg-success">Verified</div>
      <% end %>
    </h2> 
    <p class="mb-32"><%= @seller_page.business_info %></p> 
    
    <div class="justify-end card-actions">
    <% unless !user_signed_in? %>
      
    
    <% if @seller_page.user_id == current_user.id %>  
    <%= link_to seller_page_reviews_path(@seller_page.slug) do%>
      <button class="btn btn-primary-content items-center">Reviews <i class='bx bxs-message-square-check ml-4' ></i></button>
      <% end %>
    <%= link_to edit_seller_page_path(@seller_page) do%>
      <button class="btn btn-primary items-center">Edit Seller Page <i class='bx bxs-edit-alt ml-4' ></i></button>
      <% end %>
      <label for="<%= @seller_page.id %>" class="btn btn-error modal-button">Delete Seller Page <i class='bx bxs-trash-alt ml-4' ></i></label> 
      <input type="checkbox" id="<%= @seller_page.id %>" class="modal-toggle"> 
      <div class="modal">
        <div class="modal-box">
          <p class="text-lg">Are you sure you want to delete this seller page?</p> 
          <br>
          <br>
          <br>
          <div class="modal-action">
          <%=link_to seller_page_path(@seller_page), method: :delete, class:"btn btn-error" do%>
Continue
            <% end %>
            <label for="<%= @seller_page.id %>" class="btn">Cancel</label>
          </div>
        </div>
      </div>
      <% else %>
      <%= link_to seller_page_reviews_path(@seller_page.slug) do%>
      <button class="btn btn-primary-content items-center">Reviews <i class='bx bxs-message-square-check ml-4' ></i></button>
      <% end %>
      <%= link_to new_seller_page_review_path(@seller_page.slug) do%>
      <button class="btn btn-primary items-center">Add a Review <i class='bx bx-plus text-lg bold ml-4' ></i></button>
      <% end %>
<% end %>
      <% end %>
    </div>
  </div>
</div> 
<div class="card shadow-xl lg:card-side bg-primary text-primary-content col-span-2">
  <div class="card-body">
    <div class="card shadow-2xl bg-gray-50">
    <div class="card-body">
    <div class="card-title items-center text-lg"><h1 class="text-2xl">Location</h1>
      <p class='italic'><%= @seller_page.region %>, <%= @seller_page.city%></p><i class='bx bxs-location-plus flex justify-end text-5xl'></i>
    </div>

  </div>
  </div> 
  </div>
</div>
<div class="card shadow-2xl bg-primary-content lg:card-side row-span-2 col-span-2">
  <div class="card-body">
    <div class="card shadow-2xl bg-gray-50 mb-32">
    <div class="card-body">
    <div class="card-title items-center text-lg"><h1 class="text-2xl">Contact Details</h1>
      <% if user_signed_in? %>
        
      <p class='italic'>  +63<%= @seller_page.phone_number%></p> 
      <% else %>
      <p class='italic'>  +639*********</p> 
      <% end %>
      <div class="flex justify-end">
      <% if user_signed_in? %>
        
      <%= link_to @seller_page.messenger_url, class:"btn btn-info", target: :_blank do%>
      Messenger <svg xmlns="http://www.w3.org/2000/svg" class="flex justify-end py-2" width="50" height="50" viewBox="0 0 24 24" style="fill:white;transform:;-ms-filter:"><path d="M12,3c-4.92,0-8.91,3.729-8.91,8.332c0,2.616,1.291,4.952,3.311,6.479V21l3.041-1.687 c0.811,0.228,1.668,0.35,2.559,0.35c4.92,0,8.91-3.73,8.91-8.331C20.91,6.729,16.92,3,12,3z M12.938,14.172l-2.305-2.394 l-4.438,2.454l4.865-5.163l2.305,2.395l4.439-2.455L12.938,14.172z"></path></svg>
      <% end %>
      <% else %>
      <%= link_to new_user_registration_path, class:"btn btn-info", notice: "You must sign up first." do%>
      Messenger <svg xmlns="http://www.w3.org/2000/svg" class="flex justify-end" width="50" height="50" viewBox="0 0 24 24" style="fill:white;transform:;-ms-filter:"><path d="M12,3c-4.92,0-8.91,3.729-8.91,8.332c0,2.616,1.291,4.952,3.311,6.479V21l3.041-1.687 c0.811,0.228,1.668,0.35,2.559,0.35c4.92,0,8.91-3.73,8.91-8.331C20.91,6.729,16.92,3,12,3z M12.938,14.172l-2.305-2.394 l-4.438,2.454l4.865-5.163l2.305,2.395l4.439-2.455L12.938,14.172z"></path></svg>
      <% end %>
      <% end %>
      </div>
    </div>

  </div>
  </div> 
    <div class="card-actions flex justify-end">

      
  <% if @seller_page.products.count == 0%>

<% unless !user_signed_in? %>
  
  <% if @seller_page.user_id == current_user.id  %>
    
  <%= link_to new_seller_page_product_path(@seller_page), class:"btn btn-primary" do%>
      Add Products
      
  <div class="badge ml-2 badge-outline"><%=@seller_page.products.count%></div>
  <% end %>
  <% end %>
<% end %>

  <% else %>
  <%= link_to seller_page_products_path(@seller_page), class:"btn btn-primary" do%>
      View Products
      
  <div class="badge ml-2 badge-outline"><%=@seller_page.products.count%></div>
  <% end %>
  <% unless !user_signed_in? %>
  
  <% if @seller_page.user_id == current_user.id  %>
    
  <%= link_to new_seller_page_product_path(@seller_page), class:"btn btn-ghost white" do%>
      Add Products
      
  <div class="badge ml-2 badge-outline">+</div>
  <% end %>
  <% end %>
<% end %>
  <% end %>
</button> 
    </div>
  </div>
</div>

 
<% end %>
</div>

app/views/seller_pages/verify.html.erb
<% if !@seller_page.verified? %>
  <br>
  <br>
  <div class="flex justify-center">
    <div class="card shadow bg-gray-50 w-1/2" data-theme="bumblebee">
      <div class="card-body">
        <div class="bg-gray-50 flex justify-center px-3 py-28" data-theme="bumblebee">
          <div class="text-center place-items-center ">
            <div class="max-w-md justify-items-center justify-center ">
              <div class="mb-5 flex justify-center max-w-1/2">
                <%= image_tag('password.svg', class:"w-3/4 justify-center mb-10")%>
              </div>
              <div class="text-center mb-4 italic text-gray-500">A One-Time-Pin has ben sent to +63<%= @seller_page.phone_number %></div>
              <%= form_tag seller_page_otp_verification_path, method: :get do %>
                <div class="form-control">
                  <div class="flex space-x-2">
                    <%= text_field_tag :token, params[:token], placeholder: 'Enter OTP...', spellcheck: "false", class:"w-full input input-primary input-bordered" %>
                    <%= button_tag "Verify", class:"btn btn-primary" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <h1>Your account has already been verified. Thank you.</h1>
  <%= link_to "Back", seller_page_path(@seller_page) %>
<% end %>