config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :seller_pages, path: 'store' do
    resources :reviews
    resources :products
    get '/otp_verification' => 'seller_pages#verify'
  end
  resources :users, :only => [:update]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  root 'home#index'
  get 'cities/:state', to: 'application#cities'
  get '/edit_profile' => 'home#edit_profile'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
    belongs_to :seller_page
    validates :product_name, :product_description, :price, :seller_page_id, presence: true
    validates :available, inclusion: { in: [true, false] }
    validates :price, numericality: { only_float: true }
    validates :image, file_size: { less_than_or_equal_to: 25.megabytes }

  AVAILABILITY = [
    ["Available", true], ["Sold out", false],
  ].freeze

  paginates_per 3

  mount_uploader :image, ProductUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :auth_region
  before_action :set_seller_page
  # before_action :force_otp, only: %i[ new create ]
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /seller_page/:id/products
  def index
    @products = SellerPage.find_by(slug: params[:seller_page_id]).products.page params[:page]
    @seller_page = SellerPage.find_by(slug: params[:seller_page_id])
  end

  # GET /seller_page/:id/products/1
  def show
  end

  # GET /seller_page/:id/products/new
  def new
    @product = @seller_page.products.build
  end

  # GET /seller_page/:id/products/1/edit
  def edit
  end

  # POST /seller_page/:id/products
  def create
    @product = @seller_page.products.build(product_params)
    @product.seller_page_id = current_user.seller_page.id

    if @product.save
      redirect_to seller_page_products_path(@seller_page), notice: "Product was successfully created."
    else
      render action: "new"
    end
  end

  # PATCH/PUT /seller_page/:id/products/1
  def update
    if @product.update(product_params)
      redirect_to seller_page_products_path(@seller_page), notice: "Product was successfully updated."
    else
      render action: "edit"
    end
  end

  # DELETE /seller_page/:id/products/1
  def destroy
    @product.destroy
    redirect_back(fallback_location: root_path, notice: "Product was successfully deleted.")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_seller_page
    @seller_page = current_user.seller_page
  end

  def set_product
    @product = @seller_page.products.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:product_name, :product_description, :price, :available, :seller_page_id, :image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product_form.html.erb
<%= form_for([@product.seller_page, @product]) do |form| %>


<div class="card shadow-2xl bg-gray-50">
  <div class="card body px-10 py-10">
  <div class="flex justify-center">
    <div class="card shadow-inner lg:card-side bg-primary text-primary-content w-full mb-4" data-theme="bumblebee">
      <div class="card-body">
      <%if current_page?(new_seller_page_product_path)%>
        <h1 class="text-center text-3xl font-bold flex justify-center items-center">Add new Product <i class='bx bxs-note ml-4'></i></h1>
        <% else %>
        <h1 class="text-center text-3xl font-bold flex justify-center items-center">Edit Product <i class='bx bxs-edit-alt ml-4' ></i></i></h1>
        <% end %>
      </div>
    </div>
  </div>
    <div class="form-control" data-theme="bumblebee">

      <label class="label">Product Name</label>
      <div class="flex flex-col justify-center gap-x-2.5">
        <%= form.text_field :product_name, autofocus: true, autocomplete: "business name", class:"w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
      </div>
      <div class="form-control" data-theme="bumblebee">
      <label class="label">Product Price</label>
      <div class="flex flex-col justify-center gap-x-2.5">
        <%= form.number_field :price, autofocus: true, autocomplete: "business name", :step => 0.01, class:"w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
      </div>
      <div class="form-control" data-theme="bumblebee">
      <label class="label">Product Description</label>
      <div class="flex flex-col justify-center gap-x-2.5">
        <%= form.text_area :product_description, autofocus: true, autocomplete: "product description",placeholder:"Product Description", class:"textarea textarea-bordered w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
      </div>
      <div class="form-control">
        <%= form.label :available, class:"label" %>
        <div class="flex flex-col justify-center gap-x-2.5">
        <%= form.select :available, Product::AVAILABILITY,{}, class:" border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
        </div>
      </div>
      <div class="form-control" data-theme="bumblebee">
      <label class="label">Product Image(Optional)</label>
      <div class="flex flex-col justify-center">
      
        <%= form.file_field :image, accept: "image/jpeg, image/jpg, image/png", class:"w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
      </div>
      </div>
          <%= form.submit class:"btn btn-primary-content shadow-lg mt-4"%>
        </div>
        
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="card shadow h-full">
  <%= form_for([@product.seller_page, @product]) do |form| %>
  <% if @product.errors.any? %>
    
      <div class="m-2 text-center items-center mb-2">
      <div class="p-2 flex justify-center">
        <div class="flex justify-center items-center bg-white leading-none text-pink-600 rounded-full p-2 shadow text-teal text-sm">
          <span class="flex bg-red-600 text-white rounded-full h-6 px-3 justify-center items-center">Error!</span>
    <% @product.errors.each do |error| %>
    <ul>
          <li><span class="px-2"><%= error.full_message %></span></li>
    </ul>
      <% end %>
        </div>
      </div>
  <% end %>
  <% end %>
  <div class=" card-body  bg-base-200" data-theme="bumblebee">
  
    <div class="flex justify-center">
      <div class="flex justify-center mt-12">
        <div class="flex justify-center">
          <%= render 'product_form', product: @product %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="card bordered">
  <div class="card-body">
    <% if @products.present? %>
      <div class="flex justify-between items-center">
      <%= link_to seller_page_path(@seller_page), class:"btn btn-primary-content" do %>
    <i class='bx bx-arrow-back text-lg' ></i>
    <% end %><%= paginate @products %>
      </div>
      <% @products.each do |product| %>
        <div class="card lg:card-side bordered mb-6 mt-6" data-theme="bumblebee">
          <figure>
            <% if product.image.present? %>
              <%= image_tag product.image_url(:large)%>
              <% else %>
              <%= image_tag('product.svg', class:"placeholderImg py-10 px-10")%>
            <% end %>
          </figure>
          <div class="card-body">
            <h2 class="card-title"><%= product.product_name %>
            <% if product.available? %>
      
            <div class="badge badge-success mx-2">In Stock!</div>
            <% else %>
            <div class="badge badge-error mx-2">Out of Stock!</div>
            <% end %>
            </h2>
            <p><%= product.product_description %></p>
            <div class="card-actions">
              <% if product.available? %>
             <% if @seller_page.user.id == current_user.id %>
                    <%= link_to edit_seller_page_product_path(@seller_page, product), class:"btn btn-primary" do%>
                Edit Product
                <% end %>
                      <% else %>
                    <%= link_to @seller_page.messenger_url, target: :_blank, class:"btn btn-primary" do%>
                Contact Seller
                <% end %>
                    <% end %>
              <% else %>
              <% if @seller_page.user.id == current_user.id %>
                    <%= link_to edit_seller_page_product_path(@seller_page, product), class:"btn btn-primary" do%>
                Edit Product
                <% end %>
                      <% else %>
              <div data-tip="Product is out of stock" class="tooltip tooltip-bottom">
                <button class="btn btn-disabled">Contact Seller</button>
                </div>
                <% end %>
              <% end %>
              <label for="<%=product.id%>" class="btn btn-ghost modal-button">More info</label>
              <input type="checkbox" id="<%=product.id%>" class="modal-toggle">
              <div class="modal" data-theme="bumblebee">
                <div class="modal-box">
                  <div class="stats border border-base-300 mb-2">
                    <div class="stat">
                      <div class="stat-title">Product Name</div>
                      <div class="stat-value break-all"><%= product.product_name%></div>
                      <div class="stat-actions">
                        <% if product.available? %>
                          <div class="badge badge-primary"> In Stock! </div>
                        <% else %>
                          <div class="badge badge-error"> Out of Stock! </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="stat">
                      <div class="stat-title">Price</div>
                      <div class="stat-value break-all"><%= number_to_currency(product.price, unit: "&#8369;".html_safe, precision: 2) %></div>
                      <div class="stat-actions">
                        <% if @seller_page.verified? %>
                          <div class="badge badge-info"> Verified Seller </div>
                        <% else %>
                          <div class="badge badge-info"> Seller not Verified </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                  <div class="stats shadow">
                    <div class="stat">
                      <div class="stat-title">Description</div>
                      <div class="stat-desc break-normal"><%=product.product_description%></div>
                    </div>
                  </div>
                  <div class="modal-action">

                    <% if @seller_page.user.id == current_user.id %>
                    <%= link_to edit_seller_page_product_path(@seller_page, product), class:"btn btn-primary" do%>
                Edit Product
                <% end %>
                      <% else %>
                    <%= link_to @seller_page.messenger_url, target: :_blank, class:"btn btn-primary" do%>
                Contact Seller
                <% end %>
                    <% end %>

                    <label for="<%=product.id%>" class="btn">Close</label>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <br>
    <% else %>
      <br>
      <% if @seller_page.user.id == current_user.id %>
        <p>You do not have any products yet.</p>
      <% else %>
        <p>This seller does not have any products yet.</p>
      <% end %>
    <% end %>
    <%# <%= link_to "Back", seller_page_path(params[:seller_page_id]) %> 
  </div>
</div>

app/views/products/new.html.erb
<div class="card shadow h-full">
  <%= form_for([@product.seller_page, @product]) do |form| %>
  <% if @product.errors.any? %>
    
      <div class="m-2 text-center items-center mb-2">
      <div class="p-2 flex justify-center">
        <div class="flex justify-center items-center bg-white leading-none text-pink-600 rounded-full p-2 shadow text-teal text-sm">
          <span class="flex bg-red-600 text-white rounded-full h-6 px-3 justify-center items-center">Error!</span>
    <% @product.errors.each do |error| %>
    <ul>
          <li><span class="px-2"><%= error.full_message %></span></li>
    </ul>
      <% end %>
        </div>
      </div>
  <% end %>
  <% end %>
  <div class=" card-body  bg-base-200" data-theme="bumblebee">
  
    <div class="flex justify-center">
      <div class="flex justify-center mt-12">
        <div class="flex justify-center">
          <%= render 'product_form', product: @product %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h1>showing product</h1>
<p>
  <strong>Product Name:</strong>
  <%= @product.product_name %>
</p>

<p>
  <strong>Product Description:</strong>
  <%= @product.product_description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Available:</strong>
  <%= @product.available %>
</p>

<p>
  <% if @product.image.present? %>    
    <strong>Photo:</strong>
    <%= image_tag @product.image_url(:thumbnail) %>
  <% end %>
</p>

<%= link_to 'Edit', edit_seller_page_product_path(@seller_page, @product) %> |
<%= link_to 'Back', seller_page_products_path %>