config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :seller_pages, path: 'store' do
    resources :reviews
    resources :products
    get '/otp_verification' => 'seller_pages#verify'
  end
  resources :users, :only => [:update]
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  root 'home#index'
  get 'cities/:state', to: 'application#cities'
  get '/edit_profile' => 'home#edit_profile'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_seller_page
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /seller_page/:id/reviews
  def index
    @reviews = @seller_page.reviews.page params[:page]
  end

  # GET /seller_page/:id/reviews/1
  def show
  end

  # GET /seller_page/:id/reviews/new
  def new
    @review = @seller_page.reviews.build
  end

  # GET /seller_page/:id/reviews/1/edit
  def edit
  end

  # POST /seller_page/:id/reviews
  def create
    #Double prevention so that owner of seller page can't write own reviews
    if @seller_page.user_id != current_user.id
      @review = @seller_page.reviews.build(review_params)
      @review.user_id = current_user.id
      @review.reviewer_first_name = current_user.first_name
      @review.reviewer_last_name = current_user.last_name
      if @review.save
        redirect_to seller_page_reviews_path, notice: "Review was successfully created."
      else
        render action: 'new'
      end
    end
  end

  # PATCH/PUT /seller_page/:id/reviews/1
  def update
    if @review.update(review_params)
      redirect_to seller_page_review_path, notice: "Review was successfully updated."
    else
      render action: 'edit'
    end
  end

  # DELETE /seller_page/:id/reviews/1
  def destroy
    @review.destroy
    redirect_to seller_page_reviews_path, notice: "Review was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller_page
      @seller_page = SellerPage.friendly.find(params[:seller_page_id])
    end
    
    def set_review
      @review = @seller_page.reviews.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:comment, :rating, :seller_page_id, :user_id, :reviewer_first_name, :reviewer_last_name)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review_form.html.erb
<%# pass in which seller page it's for, then the review itself %>

<%= form_for([@seller_page, @review]) do |form| %>
 




<div class="card shadow-2xl bg-gray-50">
  <div class="card body px-10 py-10">
  <div class="flex justify-center">
    <div class="card shadow-inner lg:card-side bg-primary text-primary-content w-full mb-4" data-theme="bumblebee">
      <div class="card-body">
      <%if current_page?(new_seller_page_review_path(@seller_page.id))%>
        <h1 class="text-center text-3xl font-bold flex justify-center items-center">Add new Review <i class='bx bxs-note ml-4'></i></h1>
        <% else %>
        <h1 class="text-center text-3xl font-bold flex justify-center items-center">Add Review <i class='bx bxs-edit-alt ml-4' ></i></i></h1>
        <% end %>
      </div>
    </div>
  </div>
    <div class="form-control" data-theme="bumblebee">

      
      <div class="form-control">
        <%= form.label :rating, class:"label" %>
        <div class="flex flex-col justify-center gap-x-2.5">
        <%= form.select :rating, Review::RATING, {}, class:" border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
        </div>
      </div>
      <div class="form-control" data-theme="bumblebee">
      <label class="label">Seller Review</label>
      <div class="flex flex-col justify-center gap-x-2.5">
        <%= form.text_area :comment, autofocus: true, autocomplete: "product description",placeholder:"Review Comments", class:"textarea textarea-bordered w-full border border-gray-300 px-3 py-2 rounded-lg shadow-sm focus:outline-none focus:border-orange-primary focus:ring-1 focus:ring-orange-primary"%>
      </div>
      <div class="form-control" data-theme="bumblebee">
          <%= form.submit class:"btn btn-primary-content shadow-lg mt-4"%>
        </div>
        
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'review_form', review: @review %>

<%= link_to 'Show', seller_page_review_path(@seller_page.id, @review) %> |
<%= link_to 'Back', seller_page_reviews_path %>

app/views/reviews/index.html.erb
<div class="card bordered">
  <div class="card-body">
    <% if @reviews.present? %>
      <div class="flex justify-between items-center">
      <%= link_to :back, class:"btn btn-primary-content" do %>
    <i class='bx bx-arrow-back text-lg' ></i>
    <% end %><%= paginate @reviews %>
      </div>
      <% @reviews.each do |review| %>
        <div class="card lg:card-side shadow-lg mb-6 mt-6" data-theme="bumblebee">
            <figure>

              <%= image_tag('review.svg', class:"placeholderImg py-10 px-10")%>

          </figure>
          <div class="card-body">
            <h2 class="card-title"><%= review.rating %> out of 5
            </h2>
            <p><%= review.comment %></p>
            <div class="card-actions">
              <label for="<%=review.id%>" class="btn btn-primary-content modal-button">More info</label>
              <input type="checkbox" id="<%=review.id%>" class="modal-toggle">
              <div class="modal" data-theme="bumblebee">
                <div class="modal-box">
                  <div class="stats border border-base-300 mb-2">
                    <div class="stat">
                      <div class="stat-title">Rating</div>
                      <div class="stat-value break-all"><%= review.rating %> out of 5</div>
                      <div class="stat-actions">
                      <% if @seller_page.verified? %>
                          <div class="badge badge-info"> Verified Seller </div>
                        <% else %>
                          <div class="badge badge-info"> Seller not Verified </div>
                        <% end %>
                      </div>
                    </div>
                    <div class="stat">
                      <div class="stat-title">Reviewer</div>
                      <div class="stat-value break-all"><%= review.reviewer_first_name %> <%= review.reviewer_last_name%></div>
                      <div class="stat-actions">
                      
                      </div>
                    </div>
                  </div>
                  <div class="stats shadow">
                    <div class="stat">
                      <div class="stat-title">Review</div>
                      <div class="stat-desc break-normal"><%=review.comment%></div>
                    </div>
                  </div>
                  <div class="modal-action">
                    <% if review.user_id == current_user.id %>
                      <%=link_to seller_page_review_path(@seller_page.slug, review), method: :delete, class:"btn btn-error" do%>
                        Delete
                      <% end %>
                    <% end %>
                    <label for="<%=review.id%>" class="btn">Close</label>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <br>
    <% else %>
      <br>
      <% if @seller_page.user.id == current_user.id %>
        <div class="card lg:card-side shadow-lg mb-6 mt-6" data-theme="bumblebee">
            <figure>

              <%= image_tag('empty.svg', class:"placeholderImg py-10 px-10")%>

          </figure>
          <div class="card-body">
            <h2 class="card-title">Sorry, No Reviews yet...
            </h2>
            <div class="card-actions">
              </div>
            </div>
          </div>
      <% else %>
        <div class="card lg:card-side shadow-lg mb-6 mt-6" data-theme="bumblebee">
            <figure>

              <%= image_tag('empty.svg', class:"placeholderImg py-10 px-10")%>

          </figure>
          <div class="card-body">
            <h2 class="card-title">Sorry, No Reviews yet...
            </h2>
            <div class="card-actions">
              <%= link_to new_seller_page_review_path(@seller_page.slug) do%>
              <button class="btn btn-primary items-center">Add a Review <i class='bx bx-plus text-lg bold ml-4' ></i></button>
              <% end %>
              </div>
            </div>
          </div>

      <% end %>
    <% end %>
    <%# <%= link_to "Back", seller_page_path(params[:seller_page_id]) %> 
  </div>
</div>

app/views/reviews/new.html.erb
<%# Extra prevention so owner of seller page cannot write own reviews %>
<% if @seller_page.user_id == current_user.id %>
    <h1>SORRY NOPE!!! YOU CANNOT WRITE YOUR OWN REVIEWS LOL</h1>
<% else %>
<%= form_for([@seller_page, @review]) do |form| %>
  <% if @review.errors.any? %>
    
      <div class="m-2 text-center items-center mb-2">
      <div class="p-2 flex justify-center">
        <div class="flex justify-center items-center bg-white leading-none text-pink-600 rounded-full p-2 shadow text-teal text-sm">
          <span class="flex bg-red-600 text-white rounded-full h-6 px-3 justify-center items-center">Error!</span>
    <% @review.errors.each do |error| %>
    <ul>
          <li><span class="px-2"><%= error.full_message %></span></li>
    </ul>
      <% end %>
        </div>
      </div>
  <% end %>

   <div class=" card-body  bg-base-200" data-theme="bumblebee">
  
    <div class="flex justify-center">
      <div class="flex justify-center mt-12">
        <div class="flex justify-center">
          <%= render 'review_form', product: @review %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

    
<% end %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>
<br>
<br>
<p>Review: <%= @review.comment %></p>
<p>Rating: <%= @review.rating %></p>
<p>By: <%= @review.seller_page.user.first_name%></p>
<p>By: <%= @review.created_at.to_formatted_s(:long) %></p>
<% if @review.user_id == current_user.id %>
    <%# <%= link_to 'Edit', edit_seller_page_review_path(@seller_page.id, @review) %> 
    <%= link_to "Delete Review", seller_page_review_path(@seller_page.id, @review), method: :delete, data: { confirm: "Are you sure you want to delete your seller page?"} %>  
<% end %>
<%= link_to 'Back', :back %>